### ISSUE TITLE
rtorrent problems  : rTorrent: Int or String expected

### ISSUE THREAD

**Issue by gbrito** [Flexget/Flexget#1154]
While using Flexget version 1.2.521 never had problems with rTorrent.
In config.yml I use this:

`      uri: scgi://127.0.0.1:4632`

Today I updated Flexget to latest version  2.0.15.

And I have this error

`016-05-09 09:37 CRITICAL plugin        DELETE-RATIO    Couldn't connect to rTorrent: Int or String expected`

Is it possible to be a bug? Or some configuration I let it pass?

**Comment by liiight** [comment]
Please paste config and error and logs

**Comment by gbrito** [comment]
Config is the same as I used with version 1.2.521 that was working fine

[http://pastebin.com/WbQzwckE](url)

This is the error I got after using 

`flexget -L debug execute --tasks DELETE-RATIO --dump`

[http://pastebin.com/TRmpWbP4](url)

**Comment by stevezau** [comment]
hrmm.. strange. What version of python?

**Comment by gbrito** [comment]
Python 2.7.3

**Comment by stevezau** [comment]
Interesting, there is a similar issue here https://github.com/Flexget/Flexget/issues/1094

Both on python 2.7.3.. Something funny going on.. let me have a think.

**Comment by stevezau** [comment]
Can you run the following and paste the output

```
python -c "from builtins import *; from flexget.plugins.plugin_rtorrent import RTorrent; cli = RTorrent('scgi://127.0.0.1:4632'); print(cli.version)"
```

**Comment by gbrito** [comment]
```
goncalo@fr19286:~/Scripts/flexget/flexget$ bin/python -c "from builtins import *; from flexget.plugins.plugin_rtorrent import RTorrent; cli = RTorrent('scgi://127.0.0.1:4632'); print(cli.version)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/plugin_rtorrent.py", line 254, in version
    return [int(v) for v in self._server.system.client_version().split('.')]
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/plugin_rtorrent.py", line 36, in __call__
    return self.__send(self.__name, args)
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/plugin_rtorrent.py", line 133, in __request
    verbose=self.__verbose
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/plugin_rtorrent.py", line 47, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/plugin_rtorrent.py", line 64, in single_request
    addr_info = socket.getaddrinfo(host, int(port), socket.AF_INET, socket.SOCK_STREAM)
socket.error: Int or String expected
```

**Comment by stevezau** [comment]
ok good.. now run the below command and paste the output again please.. We need to try track down what is the cause.

```
python -c "from builtins import *; from flexget.plugins.plugin_rtorrent import RTorrent; cli = RTorrent('scgi://127.0.0.1:4632'); print(cli.version)"
```

**Comment by gbrito** [comment]
```
goncalo@fr19286:~/Scripts/flexget/flexget$ bin/python -c "from flexget.plugins.plugin_rtorrent import RTorrent; cli = RTorrent('scgi://127.0.0.1:4632'); print(cli.version)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/plugin_rtorrent.py", line 254, in version
    return [int(v) for v in self._server.system.client_version().split('.')]
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/plugin_rtorrent.py", line 36, in __call__
    return self.__send(self.__name, args)
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/plugin_rtorrent.py", line 133, in __request
    verbose=self.__verbose
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/plugin_rtorrent.py", line 47, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/home/goncalo/Scripts/flexget/flexget/local/lib/python2.7/site-packages/flexget/plugins/plugin_rtorrent.py", line 64, in single_request
    addr_info = socket.getaddrinfo(host, int(port), socket.AF_INET, socket.SOCK_STREAM)
socket.error: Int or String expected

```

**Comment by stevezau** [comment]
I just pushed a change that might fix it.. can u try that and let me know. You will need to use flexget git version.

**Comment by gbrito** [comment]
Just installed the flexget version from git 2.0.16.dev

And unfortunately I still have the same error

**Comment by stevezau** [comment]
hmm ok,, try this command

```
python -c "from builtins import *; import socket; from flexget.plugins.plugin_rtorrent import RTorrent; socket.getaddrinfo('127.0.0.1', 4632, socket.AF_INET, socket.SOCK_STREAM)"
```

**Comment by gbrito** [comment]
```
goncalo@fr19286:~/Scripts/flexget/flexgetgit$ python -c "from builtins import *; import socket; from flexget.plugins.plugin_rtorrent import RTorrent; socket.getaddrinfo('127.0.0.1', 4632, socket.AF_INET, socket.SOCK_STREAM)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named builtins

```

**Comment by gbrito** [comment]
Nothings gets returned

```
goncalo@fr19286:~/Scripts/flexget/flexgetgit$ bin/python -c "from builtins import *; import socket; from flexget.plugins.plugin_rtorrent import RTorrent; socket.getaddrinfo('127.0.0.1', 4632, socket.AF_INET, socket.SOCK_STREAM)"
goncalo@fr19286:~/Scripts/flexget/flexgetgit$

```

**Comment by stevezau** [comment]
hmmm ok, i'm not sure what's going on here.. are you free to join us on gitter to troubleshoot? https://gitter.im/Flexget/Flexget
