### ISSUE TITLE
console output no longer legible on narrow terminals or when piped

### ISSUE THREAD

**Issue by grr** [Flexget/Flexget#1361]
### Expected behaviour:

Long field names should be truncated to fit on the terminal width. This was the previous behavior. Or the wrapping needs fixing. Also, the colorization should be disabled when piping the output (for example through `less`)
### Actual behaviour:

Titles or other field names can be very long and cause the line to wrap and then the pretty borders that are on by default wrap oddly making it hard to read the distorted table output. I usually use 80-wide terminals, but even on a 150-wide terminal this happens if the field names are long enough (and they often are). The long field name does get wrapped, but it's very oddly done and doesn't make full use of the terminal width and the table itself wraps when the terminal is <= 113 chars. Here's a screenshot of what happens on a 150-wide terminal when the longest title is 106 characters: http://i.imgur.com/J3mSmEZ.png

Also there is an issue when colorized output is piped through less. By default `less` uses displays control characters like ^A, so maybe all colorization should be disabled when piping output. If using `less -r` the output appears ok, but if using `less -R` there are display artifacts indicating that the colorization is using sequences other than the standard ANSI color escape sequences.
### Steps to reproduce:

With a terminal sized to 150-wide, and a downloaded title at 106 characters:
`flexget history`
`flexget history | less`
The colorization issue should be apparent when using:
`flexget history | less -r`
`flexget history | less -R`
- Flexget Version: 2.3.4
- Python Version: Python 2.7.12
- Installation method: git
- OS and version: OS X 10.11.6

**Comment by liiight** [comment]
@paranoidi made some changes in `better_wrap` branch, any chance you could pull and check it out?

**Comment by grr** [comment]
Yes, the better_wrap branch looks like it solves the wrapping issue.
And the colorization issue should be solved by https://github.com/Flexget/Flexget/issues/1223#issuecomment-241567159

**Comment by paranoidi** [comment]
Should be fixed in develop now. If you find more views with same issue give us a feedback.

**Comment by grr** [comment]
@paranoidi, the colorization issue when piping is still present in develop.

**Comment by liiight** [comment]
we haven't fixed that yet, seem like an issue with the dep. I contacted the dev there.

**Comment by liiight** [comment]
@grr can you please verify?

**Comment by grr** [comment]
@liiight, I tested latest develop against both `flexget series list | less` and `flexget history | less` and the problem has **not** been fixed. It's still colorizing the output.

**Comment by liiight** [comment]
Ok, I think I get it now. I'll try to push a fix soon. Note that in the meanwhile `--porcelain` was fixed, so you could default to that for now

**Comment by y** [comment]
Typing '--porcelain' each time, especially without typos, is too much work. How about a config option like `default_cli_type`.

**Comment by cvium** [comment]
No more config options. If it's such a hassle then create an alias.

**Comment by y** [comment]
That doesn't make sense. If it's flexget config-related, it should go in the flexget config. Think how that will confuse users reporting bugs, "i'm just running flexget ...", and then a day later, "oh, i had flexget aliased to ... because somebody told me to".

**Comment by paranoidi** [comment]
I actually would like config as well, like:

    terminal:
      table_type: github
      colors: yes

or even environment variables could be used `FLEXGET_TABLE_TYPE=github`

colors should be disabled automatically based on isatty though.

**Comment by liiight** [comment]
They will, I just didn't place that function in the correct place I imagine. Need to be in each cli plugin that enables colors probably

**Comment by grr** [comment]
wasn't the wrapping issue fixed when the better_wrap branch was merged? if so, there's now a regression, because i'm seeing the same issue as shown in the image from my OP.

**Comment by liiight** [comment]
That's in the series show command, right?

**Comment by grr** [comment]
yes

**Comment by liiight** [comment]
Piping will now use `porcelain` by default if table type is not `plain`. Please try this.

**Comment by grr** [comment]
doesn't crash now, and layout appears to be porcelain, **but** the colorization is still present.

**Comment by liiight** [comment]
you're killing me here... 
can you paste output again please? and what OS are you on?

**Comment by grr** [comment]
when doing `flexget history | less` you can see colorization at the head and tail of output:
http://imgur.com/a/GNeAJ
everything in between head and tail appear to be proper porcelain. same problem with `flexget plugins | less`, `flexget failed list | less`, `flexget rejected list | less`, `flexget seen search west | less`.

and then there's other commands which are completely un-porcelain, like `flexget series list` and `flexget series show westworld`

**Comment by liiight** [comment]
1. that's not porcelain, that's single table. 
2. history doesn't use colors nor do there are any in that image... 
What version you on?

**Comment by liiight** [comment]
I was finally able to reproduce it and test a fix. I'll push it tomorrow

**Comment by grr** [comment]
you fixed the table-types but not the colorization. yes, in the above image the green was my terminal color, but in that case i was referring to the lines which were created using the ansi terminal sequences. and that should be disabled. here's an example showing colorization is still happening even after your latest change:
http://imgur.com/a/e8e10

**Comment by liiight** [comment]
man, I don't know how this is possible. I guess I'll start adding some debug logs...

**Comment by liiight** [comment]
@gazpachoking made some more changes in v2. 5.0 please try that and report back

**Comment by grr** [comment]
that fixed the colorization. but the removed highlights should be replaced with a plain ascii alternative, like '*', which was actually the behavior before colorization was added. right now we're missing information of which of the seen titles was downloaded when viewing `flexget series show westworld | less`.

also, `flexget seen search west | less` and `flexget history | less` look like they're unnecessarily adding an extra empty newline after every entry field.

**Comment by liiight** [comment]
the missing indication is known and will be taken care of.

can you give an example of what you mean with the empty line?

**Comment by cvium** [comment]
http://pastebin.com/jFKtSa8J

Seems to be caused by overflow. If I make the window wider, it'll look as it should.

**Comment by grr** [comment]
yes, it appears that even under porcelain mode, there's lots of whitespace padding being added to the end of the fields to match the length of the longest field value of the entire output, so too much whitespace is added which causes it to wrap and appear as if an extra line is added. in my case, i have a url (from `flexget history | less`) which causes it's line (`URL | ...`) to be 171 characters, but that results in every single line of output to be padded to 171 characters.

**Comment by liiight** [comment]
series show indication was fixed with https://github.com/Flexget/Flexget/commit/6fa879b7fc52ceca323e36992c66802703a8e39c

**Comment by grr** [comment]
This might also be a related issue:

    $ flexget -V
    2.8.8
    $ flexget failed list
    ERROR: Table could not be rendered correctly using it given data
    $ flexget failed list | less
    Could not start manager: 'ascii' codec can't encode character u'\xe1' in position 500: ordinal not in range(128)

**Comment by liiight** [comment]
Man, this issue is a mess now. I think it's best to close it and open a new one as many if the issues reported here are no longer relevant. 
@grr can you please open a new issue?

**Comment by grr** [comment]
ok, i created a new ticket for the last one. but do i have to also create one for 
https://github.com/Flexget/Flexget/issues/1361#issuecomment-256147795 to get that fixed or can we keep this ticket open for that?
