### ISSUE TITLE
Language selection for episode titles in thetvdb_lookup plugin doesn't work properly

### ISSUE THREAD

**Issue by PublicJohnDoe** [Flexget/Flexget#1502]
### Expected behaviour:

When using the {{tvdb_ep_name}} parameter, torrent files should be renamed to the episode title in the language selected for thetvdb_lookup.

### Actual behaviour:

No matter what I specify, the episode names are always grabbed in English.

### Steps to reproduce:
I try to get an Italian episode of The Affair, namely episode s02e08, titled "Episode 8" in English and "Una serata con l'autore" in Italian, but the filename is always named according to the English title, it seems it ignores the "language" parameter

#### Config:
```
thetvdb_lookup:
  language: it
```

#### Log:
```
2016-11-15 14:27 DEBUG    api_tvdb      task2 Looking up tvdb information for The Affair None
2016-11-15 14:27 DEBUG    api_tvdb      task2 Series <name=The Affair,tvdb_id=None> information restored from cache.
2016-11-15 14:27 DEBUG    api_tvdb      task2 Using episode info for The Affair s2 e8 from cache.
2016-11-15 14:27 DEBUG    api_tvdb      task2 Looking up tvdb information for The Affair None
2016-11-15 14:27 DEBUG    api_tvdb      task2 Series <name=The Affair,tvdb_id=None> information restored from cache.
2016-11-15 14:27 INFO     transmission  task2 "The Affair S02e08 [Mux 720p - H264 - Ita Ac3 Eng Ac3 5.1 - Sub Ita Eng]" torrent added to transmission
2016-11-15 14:27 DEBUG    transmission  task2 File The.Affair.2x08.Una.Serata.Con.L.Autore.ITA.ENG.720p.WEBMux.x264-Speranzah.mkv renamed to The Affair 2x08 - Episode 8.mkv
```

The filename is grabbed, but in English.

### Additional information:

- Flexget Version: 2.5.22
- Python Version: 2.7
- Installation method: GIT
- OS and version: Raspbian, latest version

**Comment by liiight** [comment]
Already fixed in next release, 2.6.0

**Comment by PublicJohnDoe** [comment]
It looks like it's still broken... I just tried downloading an Italian episode and this time instead of grabbing an English title it gave an empty one :(

```
2016-11-19 08:45 DEBUG    api_tvdb      t2 Looking up tvdb information for The Blacklist None
2016-11-19 08:45 DEBUG    api_tvdb      t2 Series <name=The Blacklist,tvdb_id=None> information restored from cache.
2016-11-19 08:45 INFO     transmission  t2 "The Blacklist S04e03 [Mux - XviD - Ita Eng Mp3 - Sub Ita Eng]" torrent added to transmission
2016-11-19 08:45 DEBUG    transmission  t2 File 7H3.BL4CKL157.S04E03/The.Blacklist.4x03.Miles.Mcgrath.ITA.ENG.DLMux.XviD-Pir8.avi renamed to The Blacklist 4x03 - (None).avi
```
