### ISSUE TITLE
Form plugin error for ygg

### ISSUE THREAD

**Issue by ChrisN06** [Flexget/Flexget#1996]
### Expected behaviour:
login to  https://yggtorrent.com/user/login in order to download .torrent file

### Actual behaviour:

 Exception posting login form

### Steps to reproduce:
- Step 1: ...

#### Config:
```
    form:
      url: https://yggtorrent.com/user/login
      userfield: id
      passfield: pass
      username: my_user
      password: my_password

```
  
#### Log:
```
2017-10-29 08:18 DEBUG    formlogin     yggtorrent_1080p Exception posting login form.
Traceback (most recent call last):
  File "/opt/rh/python27/root/usr/lib64/python2.7/site-packages/flexget/plugins/operate/formlogin.py", line 66, in on_task_start
    br.open(url)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/mechanize/_mechanize.py", line 254, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/mechanize/_mechanize.py", line 310, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 403: Forbidden
2017-10-29 08:18 CRITICAL formlogin     yggtorrent_1080p Unable to post login form
2017-10-29 08:18 WARNING  task          yggtorrent_1080p Aborting task (plugin: form)
2017-10-29 08:18 DEBUG    task_queue                    task yggtorrent_1080p aborted: TaskAbort(reason=Unable to post login form, silent=False)
```

### Additional information:

- FlexGet version: 2.10.104
- Python version: Python 2.7.13
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Linux CentOS release 6.9 (Final)  #1 SMP Tue Mar 18 14:48:24 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
- Link to crash log:

**Comment by primzy82** [comment]
I got the same problem on a different page

**Comment by ChrisN06** [comment]
Still not working with FlexGet version: 2.10.105

**Comment by cvium** [comment]
Why would it? No fix has been deployed.

It's most likely related to cloudflare, so it's unlikely to go away on its own...

**Comment by ChrisN06** [comment]
yggtorrent.com has been migrated and now it works for me.

**Comment by primzy82** [comment]
I'm still getting error:
...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/operate/formlogin.py", line 66, in on_task_start
    br.open(url)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 254, in open
    return self._mech_open(url_or_request, data, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 310, in _mech_open
    raise response
httperror_seek_wrapper: HTTP Error 403: Forbidden
...

**Comment by maelvls** [comment]
Hi,

I

```yaml
tasks:
  ygg_movies:
    form:
        url: https://www6.yggtorrent.lol/
        userfield: id
        passfield: pass
        username: YOURLOGIN
        password: YOURPASSWORD
    html: 
      url: https://www6.yggtorrent.lol/engine/search?category=2145&sub_category=2183&do=search&page={{i}}
      increment:
        step : 50
      links_re: [www6\.yggtorrent\.lol/torrent/]
    urlrewrite:
      yggtorrent:
        regexp: 'https://www6.yggtorrent.lol/torrent/[^/]*/[^/]*/(?P<id>\d+)-.*'
        format: 'https://www6.yggtorrent.lol/rss/download?passkey=YOURPASSKEY&id=\g<id>'
```
