### ISSUE TITLE
Transmission path is ignored

### ISSUE THREAD

**Issue by dulakm** [Flexget/Flexget#2131]
### Expected behaviour:
When I specify `path` attribute to `transmission` plugin, it is forced and the destination is set for downloading content.

### Actual behaviour:
With `path` attribute set as well as `incomplete-dir` set for transmission as a library, the library setting is used instead of `path`.

### Steps to reproduce:
- Step 1: In your transmission settings (e.g. `/etc/transmission-daemon/settings.json`) set
  - `"incomplete-dir": "/something"`
  - `"incomplete-dir-enabled": true`
- Step 2: In flexget transmission plugin specify
  - `path: "/something-else"`
- Step 3: Run your task using transmission plugin, `/something` path will be used instead of `/something-else`

#### Config:
https://github.com/zilexa/flexget_config

### Additional information:
- FlexGet version: 2.13.15
- Python version: Python 2.7.13
- Installation method: pip
- Using daemon (yes/no): no
- OS and version: Linux osmc 4.14.34-1-osmc

**Comment by gazpachoking** [comment]
Are the files being moved to the location you set in flexget once they are complete? If so, things are working as intended.

**Comment by dulakm** [comment]
Unfortunately not. Once complete, the file are still in my `incomplete-dir`. Neither they are moved to the dir specified in flexget plugin, nor to the one specified in general `settings.json`.

**Comment by gazpachoking** [comment]
Hmm. Pretty sure this worked at some point, did transmission recently update?

**Comment by gazpachoking** [comment]
@dulakm Can you check again with next version? Based on this it could have been a problem with trailing slashes in the path. https://discuss.flexget.com/t/config-for-transmission-moves-single-files-but-fails-with-folders/4586/2

**Comment by gazpachoking** [comment]
I'm going to assume this is fixed for now. We can re-open if someone finds different.

**Comment by dulakm** [comment]
@gazpachoking thank you for the fix and information. I can confirm that on `2.21.1` the issue is fixed and everything works as supposed.

**Comment by dulakm** [comment]
@gazpachoking sorry for the delay with retesting. Unfortunately when running version `2.21.1` the issue is still present.

**Comment by dulakm** [comment]
@gazpachoking thank you for the fix and the information! I can confirm that it works as expected on version `2.21.1`.
