### ISSUE TITLE
PIP installed Flexget doesn't load WEB UI

### ISSUE THREAD

**Issue by TnTBass** [Flexget/Flexget#4130]
Just updated flexget to 3.13.8 and I get the notice that it looks like I installed flexget via github, and I need to run the WEB UI build steps. However, I installed this via PIP so I would not expect this to be a requirement.

Possibly related to: https://github.com/Flexget/Flexget/issues/4129

```
Failed to load Flexget Web UI
It looks like you are running flexget from the GitHub source. If you want to use the webui you'll have to run the WebUI build steps by following https://flexget.com/Web-UI
```

### Expected behaviour:

Expect the WEB UI to load

### Actual behaviour:

WEB UI generates an error

- FlexGet version: 3.13.8
- Python version: Python 3.12.3
- Installation method: PIP
- Using daemon (yes/no): yes
- OS and version: Ubuntu 24.04

**Comment by gazpachoking** [comment]
Yeah, same as #4129. Fixed release will be out today, sorry about that

**Comment by TnTBass** [comment]
Thanks @gazpachoking - its fixed now in v3.13.9

**Comment by gazpachoking** [comment]
Looks like this is still a problem for Rasperry Pi OS users (or anyone who is using piwheels as an extra index for pip) because they are providing a wheel that doesn't have the webui bundled. I've opened a ticket there to see if we can have that fixed.
https://github.com/piwheels/packages/issues/493

**Comment by gazpachoking** [comment]
Raspberry pi users may be able to work around this for now by using the `--isolated` flag for pip when installing (i.e. `pip --isolated install flexget`), or removing the `/etc/pip.conf` file if they don't care about using the piwheels repo for other wheels.

**Comment by gazpachoking** [comment]
piwheels removed flexget from their index (there is no need to rebuild our wheel for rpis, it's already pure python) so now everything should work again.
